### PR TITLE
Align color output with less.js

### LINKED ISSUE #168: Color shortening
I know that this implementation shortens colors if they fall into a human readable color (ex: #ffffff returns 'white' instead). This is great for making code smaller, but for implementations with filters (in mixins) the hex code is what is needed to render properly. Can this possible be changed or at least configured as a loadtime setting?

### PR DESCRIPTION
**Pull request by yln**
* We now don't change/compress colors when user specifies the color (keyword, or any form of #hex).
* Computed colors (i.e., hsl, rgba, etc..) now always have the full hex form: #112233
* Removed a few special cases (e.g., `rgba(0,0,0,0) -> transparent`) to align with less.js
* Adapted a lot of tests (very tedious work :()
* Removed `DisableColorCompression` compiler flag (colors are never compressed now)
* Refactorings / cleanup
* A few more tests from the less.js test suite are green now

It felt a bit bad to remove some smarts of dotless, i.e., `#1122331 -> #123` or the transparent special case: they save some bytes and don't really hurt readability.

Fixes #168.

### CODE REVIEW

**Comment by rytmis** [comment]
Yikes, sorry for being AWOL for so long. This looks like great work!

I'm a bit nervous about making C# API breaking changes prior to 2.0, so I'll have to give this some thought before I merge it in. :)

**Comment by Tigraine** [comment]
@rytmis Have you had time to look at this? It seems good to me and if we could avoid the breaking API changes I don't see a reason not to merge this.

**Comment by rytmis** [comment]
Yeah, other than the API breakage, I'm good with this. Previously, I've tried to maintain compile-time ABI even if the features have been removed -- at least LessEngine and Color have changes in this set that will break it though.

I'm mostly concerned for things like System.Web.Optimization.Less, because breaking the ABI is not SemVer-compliant, and they might end up with an incompatible dotless. 

End users that use dotless directly are not so likely to run into those issues.

**Comment by rytmis** [comment]
I'm merging this in now, and the result has a bunch of tests failing because the tests expect keyword colors and we now produce hex values. That's fine, and it won't take long for me to fix those -- but looking at the test outputs, I'm left wondering whether we should _always_ output hex values. It seems weirdly inconsistent that we normalize some values but not others.

**Comment by rytmis** [comment]
Btw. in case you guys are curious, here's a quick analysis of the API-breaking method-level changes in this PR compared to dotless 1.5.2:

image

**Comment by rytmis** [comment]
I reverted the cleanups on that list for now. Don't get me wrong: I think Julian's changes were the sort that I'd make when cleaning up, too -- it's just that a change like this, I'd like to keep SemVer compliant. :)

**Comment by Tigraine** [comment]
Great work @rytmis! :+1:

**Pull request merged**
