### PR TITLE
Convert to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by twenzel**
* Converts dotless.Core to .NET Standard 2.0 (including tests)
* Removes Pandord IoC. Replaced by Microsoft.Extensions.DependencyInjection
* Updated other projects to .NET 461

### CODE REVIEW

**Comment by Tigraine** [comment]
Very cool.. I'll have a look at this during the week. Thanks!

**Comment by Tigraine** [comment]
Which DI does this use under the covers? I I understand correctly `Microsoft.Extensions.DependencyInjection` is similar to the old Common ServiceLocator Pattern which we did support back then right?

**Comment by twenzel** [comment]
`Microsoft.Extensions.DependencyInjection' is a tiny & lightweight IoC framework which is widely used in all modern .NET Core (mostly ASP.NET Core) applications. It's not a ServiceLocator pattern anymore it's a real IoC framework. It's also extensible to be used with Castle Windsor or Autofac.

I've moved to this IoC because this dependency is mostly already within many modern applications, and I didn't want to convert the Pandora library also.

**Comment by twenzel** [comment]
The next step is to create dedicated Nuget packages (e.g. dotless.Core, dotless.AspNet, dotless.Compiler).
This is what I'm currently working on.

**Comment by twenzel** [comment]
Short question: What is the /lib/PegBase.dll used for? Or the PEG_GrammarExplorer?
What is the t4css used for? Sorry for asking, I just want to understand what this project is all about.

**Comment by Tigraine** [comment]
I think these are old libraries that were there before James did the
less.ja rewrite. I doubt they are still used.

T4css I’ll delete all together. That was a visual studio template engine
nobody was seriously using but seemed like a good idea back in 2010..

Great that there now is a Mini IOC that does all these things. I did not
want to include a full fledged heavy IOC container that’s why I wrote
pandora back then to just barely satisfy servicelocation and have something
lightweight available out of the box.

Great work! Thanks.

**Comment by twenzel** [comment]
Which version/features of less.js is currently implemented? 1.7.5? Just to get the compatibility tests running.

**Comment by Tigraine** [comment]
@lauri can help with that. I think we are around 1.5 IIRC?

**Comment by rytmis** [comment]
The unfortunate truth is that we don't support any particular strict version of the less language -- last I checked, the truth was [something like this](https://github.com/dotless/dotless/issues/457#issuecomment-115211097).

**Comment by twenzel** [comment]
Hi @Tigraine and @rytmis , do you might have a look at the 
[new build branch](https://github.com/twenzel/dotless/tree/feature/BuildCorePackage) and try to get the compatibility tests running/working? 
At the moment it uses the 1.5.0 less.js version and 3 tests are failing. It would be awesome to get those tests succeeding as well. You might change the less.js version (in app.config) if it helps.

**Comment by rytmis** [comment]
The compatibility tests seem to be ignored to a large degree. Of the three failures, one of them is clearly a case of Dotless behaving differently (albeit not in an incompatible way -- color keywords are replaced with the hex constant) and two of them seem to involve files that aren't actually generated at all (the corresponding less files exist, but no output css).

At this point, I'm fine with ignoring the compat test suite. It was a work in progress anyway. :)

**Comment by twenzel** [comment]
At the moment I've following nuget packages identified:
* dotless.core -> core features
* dotless.AspNet -> AspNet HttpHandler + dependecy dotless.core
* dotless -> meta package for backward compatibility + dependecy dotless.core, dotless.AspNet

Should we include the dotless.compiler.exe within the dotless package under "tools"? Or should we create another package (e.g. dotless.CLI)?

**Comment by Tigraine** [comment]
No real preference here. But when I want a CLI application I'd probably use something like chocolatey right? Either way fine with me - whatever makes more sense..

**Comment by twenzel** [comment]
I'll close this pull request in favor of a [new one](https://github.com/dotless/dotless/pull/536) containing all including running build scripts.

**Pull request closed without merging**
