### PR TITLE
- fix issue #510

### PR DESCRIPTION
**Pull request by kingatlas**
Related to issue #510

### CODE REVIEW

**Comment by rytmis** [comment]
So, am I reading this right? Was this an operator precedence issue?

**Comment by kingatlas** [comment]
Yes that was related to the left associativity of the && operator.

**Comment by rytmis** [comment]
All right. Thanks for taking the time to figure this out. Do you suppose you could write a unit test that verifies this fix, and do the existing tests all still pass with this change?

**Comment by kingatlas** [comment]
I have just added a new unit test "KeyFrameDirective5" to cover the case.

**Comment by rytmis** [comment]
Thanks, and sorry for taking this long to react -- rather busy right now. I will try to get this merged in this week.

**Comment by Tigraine** [comment]
Sorry it took so long. I merged this. Thanks a lot @kingatlas!
A little pointer for next time: Please name your commits to actually reflect what they did. Fix #511 makes a lot of sense to the three of us following this conversation - but to someone reading the history not so much. You can always reference the issue in the description of the commit (second line) and it would also make it easier for us to generate changelogs off the history etc.

**Pull request closed without merging**
