### PR TITLE
Fix error Failed to start monitoring file changes.

### PR DESCRIPTION
**Pull request by marcoippel**
## The problem:

We are using episerver in combination with dotless. When you edit a less file the cache is cleared and the compiled less is inserted in the cache. 

The issue is that on some way the cache dependencies contains folders that are a combination of a absolute file path and a relative url for example:

Directory 'D:\inetpub\samplesite\samplewebsite.website\contactus\' does not exist. Failed to start monitoring file changes.

Let's say "D:\inetpub\samplesite\samplewebsite.website\" is the path on the server where the site is installed.

"/contactus" is the url requested. If now the content of a less file is changed the cache is invalid and needs to be refreshed and the cachedependency folder is set to "D:\inetpub\samplesite\samplewebsite.website\contactus\".

This folder doesn't exist and the cache insert throws an error.
## The fix:

Foreach directory in the file dependencies collection a check is done if the directory exist.
If not don't add it to the existingFullPaths collection. 

If the existingFullPaths contains any entry add the existingFullPaths as cache dependency to the cache object.

### CODE REVIEW

**Comment by rytmis** [comment]
Thanks for finding this. A couple of questions:

- Do you know if this is a regression from dotless 1.4? I seem to recall touching import path handling during 1.5 development.
- Is this something that can be easily reproduced with a non-episerver site? 
- If so, do you think you could provide a sample so that I could verify that this is the correct way to fix the problem? I'm thinking perhaps this is something that should be handled by the importer, not the cache layer.

**Comment by marcoippel** [comment]
Hi Lauri,

We updated the dotless tot version 1.5 because i found on the internet it
should be fixed.

I think i van make a sample mvc site with the same logic as is the
episerver site.

This issue happens when we are developing normally we don't change less
files without a deployment.

I will see if i can make an example and sent it to you.

Marco
Op 4 jun. 2015 9:34 PM schreef "Lauri Kotilainen" <notifications@github.com

**Comment by marcoippel** [comment]
I created a project and commited it on [GitHub](https://github.com/marcoippel/DotLess-reproduce-project) 

You can reproduce teh problem on the following way:
* Go to "http://localhost:1329/Home/Contact" is must be a page beow the homepage.
* Attach a debugger to dotless.Core.Cache.HttpCache on the method "public void Insert(string cacheKey, IEnumerable<string> fileDependancies, string css)"
* While debugging change a .less file.
* This triggers the cachedependency and creates a new cache object with a file dependency.
* Check the filenames array this contains 1 entry with path "D:\Github\DotLess-reproduce-project\DotLess Reproduce project\Home"
* This is a none existing path and in episerver it throws an error but strange enough here it doesn't but the cache dependency is on a none eisting path.

I hope it helps to to reproduce the bug if you have any question please let me know.

Regards,
Marco

**Comment by rytmis** [comment]
Thanks, I'll take a look at it in the next few days!

**Comment by rytmis** [comment]
OK, so I've had time to look at the issue for a moment, and it looks like the trigger is that when we're dealing with a bundle, we don't have a file name, so it's set to `null`. That `null` gets passed on to `HttpContext.Current.Server.MapPath`, which in turn produces the nonexistent path. I'm too tired to follow through the entire chain of logic within that method, but for me, in `/Home/Contact` the path ended up being `<rootDir>\Home`.

Now, I'm thinking perhaps the correct thing to do here is to filter out `null` dependencies in HttpCache.Insert before resolving paths for them -- that is, changing this line:

```CSharp
var fullPaths = fileDependancies.Select(f => PathResolver.GetFullPath(f)).ToArray();
```

to this:

```CSharp
var fullPaths = fileDependancies.Where(d => !string.IsNullOrEmpty(d)).Select(f => PathResolver.GetFullPath(f)).ToArray();
```

Could you please see if that fixes the issue for you?

Also, I'm interested to hear what exception you are getting in your EpiServer environment.

**Pull request closed without merging**
