### PR TITLE
SourceMaps for dotless

### PR DESCRIPTION
**Pull request by corelgott**
Even though this is an early stage, I would be glad to get some feedback about this feature. There are still some things to do to get it ready for a "normal" release. But non the less, the biggest chunk (beside the testing) is done. To get some info about the current state take a look at my project markdown.

cheers,

corelgott

### CODE REVIEW

**Comment by TryingToImprove** [comment]
+1

**Comment by rytmis** [comment]
I'm planning to work through the [1.5.0 to-do list](https://github.com/dotless/dotless/milestones/1.5.0) before I look at source map support, so near-term progress on this front is not very likely.

**Comment by madskristensen** [comment]
+1

**Comment by Booster2ooo** [comment]
+1

**Comment by drowhunter** [comment]
+1

**Comment by jmwolfe** [comment]
+1

**Comment by NanoWar** [comment]
+1

**Comment by Tigraine** [comment]
Closed due to inactivity - sorry about that :(

**Pull request closed without merging**
