### PR TITLE
Added support for various @import options

### PR DESCRIPTION
**Pull request by rytmis**
First implementation was for a single option of a given type, but then I gathered from less/less.js#1185 that some option combinations (e.g. @import (less, reference) "somefile.css") should work, so I added support for combinations.

Some combinations clearly don't make sense (e.g. @import (css, less) "somefile"), so I decided to throw a parser exception on the invalid combinations I could think of. I'm sure there are cases that I didn't, along with valid feature combinations that don't yet quite do what they should. But it's a start.

I duct-taped a separate "Normalized line endings" commit in between the first two commits, because when I was writing this note, I noticed that the diff for Importer.cs didn't look right -- apparently, the line endings were mixed and I offhandedly had asked VS to normalize them... :angry:  It still doesn't look right in the PR, but the individual commits after that should be readable.

### CODE REVIEW

**Comment by rytmis** [comment]
Trying out with more complex examples (Bootstrap), I'm noticing that @import (reference) is not quite there yet.

**Comment by rytmis** [comment]
Merged into develop.

**Comment by RichardWright** [comment]
@rytmis Hi! Is this the same feature you mentioned here(http://stackoverflow.com/questions/28822531/import-reference-doesnt-work#comment45932018_28822531)? I'm interested in when this feature might be ready.

**Comment by rytmis** [comment]
@RichardWright Indeed it is. It should be supported now, with the caveat that obviously it's not very well battle-tested yet. :)

**Pull request closed without merging**
