### PR TITLE
System.Web.Optimization bundling for dotless

### PR DESCRIPTION
**Pull request by helephant**
I've added a library to the project that has a bundle transformer for less files for the System.Web.Optimization framework. Bundling actually turned out a lot easier than the existing web handler because the bundling takes care of things like caching and gzip.

I've debugged it on sample projects at home and am going to try it on a real project at work next week (provided my team are understanding!).

It doesn't have a good solution for debugging files at the moment, but I think compiling less files should work in most situations. I didn't support parameters because it wasn't a feature that I needed. 

System.Web.Optimization requires .NET 4 so I've added bundling as a separate project. I also upgraded the Test project so I could put the bundling tests in with the others. Adding a .NET 4 meant I had to upgrade psake, nunit and ilmerge to their latest version to be able to deal with the .NET 4 assemblies.

I created a new nuget package for people who just want to use less for bundling. It installs the less web.config and has the right assembly. I didn't want to add it to the main package because of the .NET 4 dependency. 

I wasn't sure I used the IOC container correctly since I wanted to make sure it wasn't visible to people using the LessBundle or LessTransform classes. Let me know if I need to change it (or could just do it better).

### CODE REVIEW

**Comment by rytmis** [comment]
Hey, this is a rather involved-looking PR, so before I take a deeper look, I thought I'd ask how this relates to this package: https://github.com/scott-xu/System.Web.Optimization.Less -- is the PR still relevant if you use dotless via S.W.O.Less?

**Comment by helephant** [comment]
It's almost done. I just wanted to make a change to the way the files are combined but never got back to it. I tried to make it possible to declare variables in one less file in the bundle and use them in a later one because we use less files for branding our website in different ways. It didn't work but might now that you've changed the way the variables are evaluated? 

Is the system.web.optimization.less a Microsoft package? Otherwise, doesn't it make sense to have bundling that lives with the project? I couldn't find a less system.web.optimization package when I did the work though.

**Comment by helephant** [comment]
If you think it's worth merging, I'll finish it off. Otherwise if you think that the existing one is the best way to go, that's cool too. :)

**Comment by rytmis** [comment]
Taking a closer look at what you've done, it's very similar to what I have in a couple of my projects that use bundling with less. Having also looked at S.W.O.Less, I think their bundling support is more mature -- they've implemented a virtual file reader that handles import resolution, bundle caching that takes dependencies into account and so on.

I'm of the opinion that it makes sense to ship bundling in a separate NuGet package, which means it isn't a big concern that the package lives in another repository. So I'm leaning towards keeping the work done in S.W.O.Less -- it's not a Microsoft package, but it does seem to have been field tested with over 40k NuGet downloads. :-)

BTW regarding your issue with imported variables: that's always worked for me, provided that I have a master file that imports both the defining and the calling file. If your scenario is that you would have liked to include the two files using the bundling API and then have it work, I suspect that the solution would be to first concatenate the file contents and only then do the LESS parsing on them.

**Comment by rytmis** [comment]
Oh, and in case it wasn't obvious, S.W.O.L uses dotless as its engine, so it's not a duplication of that effort. :-)

**Comment by helephant** [comment]
Ok. That's fine then. :)

**Pull request closed without merging**
