### PR TITLE
less.js compatibility test suite

### PR DESCRIPTION
**Pull request by yln**
This is a first attempt for #450.

The workflow with this should be something like the following:
1. Clone less.js to local folder
2. Point the `dotless.CompatibilityTests` to that folder
3. Run tests
4. Failing tests dump `xxx.actual` and `xxx.expected` into a `differences` folder for easy comparison with diff tools
5. Edit `ignore.txt` for tests we want to exclude, add a comment after `;` which is shown as the ignore reason in test runners

__Rationale__:
* I don't think we want to port the tests. That's too much required effort/maintenance. I think not even having them in our repository is the best way to go. Updating the tests should be as easy as `git pull` in `less.js` (hopefully).
* Making `ignore.txt` a black-list, instead of a white-list: We automatically notice when less.js adds new tests that fail for us. The *goal* should be to make ignore.txt empty.

Open points:
- [x] Location of less.js project is hard-coded in string constant. How should we make this configurable for every developer machine? (search for `TODO(yln)`)
- [x] Large classes of tests are still failing due to other reasons than differing outputs (e.g., `errors` sub-directory, or `*.less` input files that have no 1-to-1 mapping with a `*.css` output file).
- [x] How should we compare the output? Do we compare about formatting? (search for `TODO(yln)`)
- [x] There is more stuff under `less.js/test` then `less` and `css`. Do we care about this?
- [x] Allow running of individual tests or a group of tests to speed up dev cycle. It's still pretty fast, so low priority for now.

### CODE REVIEW

**Comment by rytmis** [comment]
Oh wow. This is a great way to wake up in the morning -- I never thought _this_ would elicit a pull request, but I'm happy that it did.

> Location of less.js project is hard-coded in string constant. How should we make this configurable for every developer machine? (search for TODO(yln))

My original thought for this was to have tooling in the project that would clone less.js -- that way, if we want, we can pin it to a specific version, so the pass/fail ratio won't change between machines just because different less.js versions. What do you think?

> Large classes of tests are still failing due to other reasons than differing outputs (e.g., errors sub-directory, or *.less input files that have no 1-to-1 mapping with a *.css output file).

While the goal is obviously to get them running, but these don't necessarily need to be tackled within the context of this PR. I'm thinking the compat test suite will primarily be there to guide dotless development for now, not act as a build gate. Yet.

> How should we compare the output? Do we compare about formatting? (search for TODO(yln))

This could be tricky. Can we force less.js to indent like dotless does? If not, then non-meaningful whitespace differences should probably be ignored.

Awesome work. Can't wait to look into this. :)

**Comment by yln** [comment]
>> How should we compare the output? Do we care about formatting? (search for TODO(yln))

> This could be tricky. Can we force less.js to indent like dotless does? If not, then non-meaningful whitespace differences should probably be ignored.

Okay, I will look into this.

>> Large classes of tests are still failing due to other reasons than differing outputs (e.g., errors sub-directory, or *.less input files that have no 1-to-1 mapping with a *.css output file).

> While the goal is obviously to get them running, but these don't necessarily need to be tackled within the context of this PR. I'm thinking the compat test suite will primarily be there to guide dotless development for now, not act as a build gate. Yet.

Yeah, I think it's a first step. I can keep iterating on the infrastructure once we have a few more tests passing. Also: we can make it part of the build now and simply ignore all the tests that are not passing yet. This at least ensures that things that pass now, will pass in the future.

>> Location of less.js project is hard-coded in string constant. How should we make this configurable for every developer machine? (search for TODO(yln))

>My original thought for this was to have tooling in the project that would clone less.js -- that way, if we want, we can pin it to a specific version, so the pass/fail ratio won't change between machines just because different less.js versions. What do you think?

With tooling you mean invoking git from C#, right? I agree, the idea of clicking "Run Tests" and everything works automatically seems very appealing. However, right now I don't think it's worth the effort to implement that: invoking git on different platforms might be trickier than expected (or use git .net library/bindings?), what if the download fails?, what if git is not installed at all?, where to download the project to?, when to re-download?. If we leave it to the developer we don't have to answer any of these questions. On the build server we can pick an arbitrary version and be fine. For the few developers I hope that "Fails/Works for me with version #hash" is good enough (for this PR).

My TODO question was simply about: What is the common practice to pass configuration values to tests? `app.config`? How do we handle that in git? (Nothing is more annoying than that one file that you modified but not allowed to commit.)

**Comment by rytmis** [comment]
>With tooling you mean invoking git from C#, right? I agree, the idea of clicking "Run Tests" and everything works automatically seems very appealing. However, right now I don't think it's worth the effort to implement that: invoking git on different platforms might be trickier than expected (or use git .net library/bindings?), what if the download fails?, what if git is not installed at all?, where to download the project to?, when to re-download?. If we leave it to the developer we don't have to answer any of these questions. On the build server we can pick an arbitrary version and be fine. For the few developers I hope that "Fails/Works for me with version #hash" is good enough (for this PR).

I was thinking more along the lines of having a script that would call out to git -- possibly a grunt/gulp task or something to that effect, so it would be easier to run xplat -- so it wouldn't be tied to the C# tests at all. I'd start with the assumption that Git is installed.

In any case, you're the one currently working on this, so you're free to go about it in whatever manner you deem best.

>My TODO question was simply about: What is the common practice to pass configuration values to tests? app.config? How do we handle that in git? (Nothing is more annoying than that one file that you modified but not allowed to commit.)

That, or environment variables are fine, too. .NET 3.5 doesn't leave us with very many built in alternatives.

**Comment by yln** [comment]
> [...] possibly a grunt/gulp task or something to that effect, so it would be easier to run xplat [...]

I don't have a lot of experience with this (read: none), so just making the path configurable for now.

For comparing the outputs there are a few additional points:
* minor differences in formatting: the easiest thing here would be to simply align our output with less.js
* less.js doesn't minify by default, e.g., comments are not pruned. Minification is done via a plugin. The tests use the default settings and the plugin probably has it's own tests. Is there a similar plugin mechanism in dotless? Is there a switch to turn off minification? Or should we run less.js dynamically with minification enabled and then compare the outputs?

Can we merge this, so I can iterate on the output in a new PR?

**Comment by rytmis** [comment]
Yeah, sure. I'll try to get it merged in today. Note that I've worked on the `develop` branch and merged releases on to master, so I'll merge it there. :)

**Comment by rytmis** [comment]
This should now be merged into the develop branch. I did zero testing, because I'm in the middle of doing some rather heavy house renovation work right now. I hope you can work off of this? If you make further PRs, could you please make them against the develop branch, too?

**Pull request closed without merging**
